### ISSUE TITLE
Login Register U.I broken

### ISSUE THREAD

**Issue by lrnzdc3696** [YameTechs/website#16]
![Screenshot_20220124-143412](https://user-images.githubusercontent.com/77531972/150733636-b06d5233-1c7c-4189-9a52-4cf303508c4a.png)
![Screenshot_20220124-143417](https://user-images.githubusercontent.com/77531972/150733650-383ffad3-a3c5-4ea7-a047-23018aa3ceba.png)

**Comment by lrnzdc3696** [comment]
Adding this 
![Screenshot_20220124-143951](https://user-images.githubusercontent.com/77531972/150734162-ed9f6c52-1e5c-45ca-91e3-37957c0fd029.png)

**Comment by federico101** [comment]
worling on it

**Comment by lrnzdc3696** [comment]
The UI is now kinda fixed but it is not responsive

**Comment by lrnzdc3696** [comment]
It would be nice if the msg below is somewhat readable

maybe just put `Register Now` and `Forgot your password?`
![Screenshot_20220202-155326](https://user-images.githubusercontent.com/77531972/152114778-cdf2e40f-e914-4064-b197-9b52e1bc4545.png)

**Comment by lrnzdc3696** [comment]
@federico101 I have found the login nor register not working bug it was something on username I will be making a test for this later on and a commit that fixes this

**Comment by lrnzdc3696** [comment]
I have also found the flash msg here it is.
![Untitled11_20220203105648](https://user-images.githubusercontent.com/77531972/152274045-ab1fe74d-d873-4df4-ad95-c7a342fbc344.png)

**Comment by lrnzdc3696** [comment]
@federico101 any update on this?

**Comment by federico101** [comment]
cant merge yet

**Comment by federico101** [comment]
i mean pull req, i haven't fixed the conflicts yet

**Comment by lrnzdc3696** [comment]
alright

**Comment by federico101** [comment]
check latest pull req

**Comment by federico101** [comment]
![20220212_230144](https://user-images.githubusercontent.com/68512132/153716464-a4a346a2-a4dc-40d6-ab13-9b06bc0c37ce.jpg)

is this okay?

**Comment by lrnzdc3696** [comment]
Yup

**Comment by lrnzdc3696** [comment]
Fixed on #41
