### ISSUE TITLE
Logout button where?

### ISSUE THREAD

**Issue by lrnzdc3696** [YameTechs/website#17]
When a person is logged in, you can't see the logout button

**Comment by federico101** [comment]
![logout](https://user-images.githubusercontent.com/68512132/151298669-8650d535-1567-4270-a020-d13e0d725045.png)

what do you think

**Comment by federico101** [comment]
working on it

**Comment by federico101** [comment]
check it

**Comment by lrnzdc3696** [comment]
I have tested the code and you made many bugs
**PLEASE DON'T PUSH CODES INTO MAIN**
please just push to dev

1. I can't see the register button
2. The login doesn't work anymore
3. The register doesn't work anymore
4. The U.I for android is broken
5. There shouldn't be a guest picture and name 
6. I can't see errors on login

**Comment by lrnzdc3696** [comment]
I have made a new branch dev but please make pull requests

**Comment by lrnzdc3696** [comment]
This was fixed in #14 I think

**Comment by lrnzdc3696** [comment]
This was fixed in #14 I think
